# Generated by Django 5.1.4 on 2024-12-20 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 20, 14, 1, 56, 574600, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
