# Generated by Django 5.1.4 on 2024-12-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0006_remove_notification_user_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
