# Generated by Django 5.1.4 on 2024-12-22 07:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='table',
            name='name',
        ),
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.table'),
        ),
        migrations.AddField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='seats',
            field=models.PositiveIntegerField(choices=[(2, '2 Kişilik'), (4, '4 Kişilik'), (6, '6 Kişilik'), (8, '8 Kişilik')], default=2),
            preserve_default=False,
        ),
    ]
