# Generated by Django 5.1.4 on 2024-12-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.PositiveIntegerField(choices=[(2, '2 Kişilik'), (4, '4 Kişilik'), (6, '6 Kişilik'), (8, '8 Kişilik')], default=2),
        ),
    ]
